/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

extern "C" {
JNIEXPORT jlong JNICALL
Java_com_apress_wavplayer_AbstractPlayerActivity_open(JNIEnv *, jobject, jstring);
JNIEXPORT jdouble JNICALL
Java_com_apress_wavplayer_AbstractPlayerActivity_getFrameRate(JNIEnv *, jobject, jlong);
JNIEXPORT jint JNICALL
Java_com_apress_wavplayer_AbstractPlayerActivity_getHeight(JNIEnv *, jobject, jlong);
JNIEXPORT jint JNICALL
Java_com_apress_wavplayer_AbstractPlayerActivity_getWidth(JNIEnv *, jobject, jlong);
JNIEXPORT void JNICALL
Java_com_apress_wavplayer_AbstractPlayerActivity_close(JNIEnv *, jobject, jlong);
JNIEXPORT jboolean JNICALL
Java_com_apress_wavplayer_AbstractPlayerActivity_render(JNIEnv *, jobject, jlong, jobject);

JNIEXPORT jlong JNICALL
Java_com_apress_wavplayer_OpenGLPlayerActivity_init(JNIEnv *, jclass, jlong);
JNIEXPORT void JNICALL
Java_com_apress_wavplayer_OpenGLPlayerActivity_initSurface(JNIEnv *, jclass, jlong, jlong);
JNIEXPORT jboolean JNICALL
Java_com_apress_wavplayer_OpenGLPlayerActivity_render(JNIEnv *, jclass, jlong, jlong);
JNIEXPORT void JNICALL
Java_com_apress_wavplayer_OpenGLPlayerActivity_free(JNIEnv *, jclass, jlong);

JNIEXPORT void JNICALL
Java_com_apress_wavplayer_NativeWindowPlayerActivity_init(JNIEnv *, jclass, jlong,jobject);
JNIEXPORT jboolean JNICALL
Java_com_apress_wavplayer_NativeWindowPlayerActivity_render(JNIEnv *, jclass, jlong, jobject);

}