/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

extern "C"
JNIEXPORT void JNICALL
Java_com_apress_wavplayer_jni_FmodJni_fix(JNIEnv *env, jobject instance,
                                                    jstring fileName_, jint type);