/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_apress_wavplayer_jni_JniTest */

#ifndef _Included_com_apress_wavplayer_jni_JniTest
#define _Included_com_apress_wavplayer_jni_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_apress_wavplayer_jni_JniTest
 * Method:    getJniString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_wavplayer_apress_com_wavplayer_jni_JniTest_getJniString
  (JNIEnv *, jobject);

/*
 * Class:     com_apress_wavplayer_jni_JniTest
 * Method:    play
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_apress_wavplayer_jni_JniTest_play
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif